### ISSUE TITLE
"code":-32601,"message":"Method not found" No payments

### ISSUE THREAD

**Issue by newpoolpw** [leviarcoin/leviarcoin-pool#5]
Все решено!
All solved!

**Comment by ghost** [comment]
i found an issue here
change 
    },
    "wallet": {
        "checkInterval": 60,
        "rpcMethod": "getBalance"
    }

to
    "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }

**Comment by newpoolpw** [comment]
Все решено!
All solved!
